# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
- name: 🙋  Usage Questions
  url: https://github.com/osl-incubator/osl-python-template/discussions
  about: |
    Use OSL Python Package Template GitHub Discussions to ask "How do I do X
    with the OSL Python Package Template?".
- name: 📖  Tutorial
  url: https://github.com/osl-incubator/osl-python-template
  about: |
    The OSL Python Package Template tutorial is continually updated and provides
    an in depth walkthrough of how to use the latest release of OSL Python Package Template.
- name: 📝  OSL Python Package Template Code of Conduct
  url: https://github.com/osl-incubator/osl-python-template/blob/main/CODE_OF_CONDUCT.md
  about: Expectations for how people will interact with each other on OSL Python
  Package Template GitHub.
